const ACCOUNT_ID = '1165561124';
const PROMOTIONS_SHEET_NAME = 'Promotions - Second Priority After Dashboard';

const {
  SWEEPERS_SPREADSHEET,
  SWEEPER_NAME,
  THRUTEXT_TOKEN
} = process.env;

module.exports = {
  ACCOUNT_ID,
  SWEEPERS_SPREADSHEET,
  PROMOTIONS_SHEET_NAME,
  SWEEPER_NAME,
  THRUTEXT_TOKEN
};