const ACCOUNT_ID = '1165561124';
const SWEEPERS_SPREADSHEET = '1KAr6YLEEmIjxKBCMjTYEtFIzwn3yHefZ00aVyVUzK3M';
const PROMOTIONS_SHEET_ID = '500563965';
const PROMOTIONS_SHEET_NAME = 'Promotions - Second Priority After Dashboard';

module.exports = {
  ACCOUNT_ID,
  SWEEPERS_SPREADSHEET,
  PROMOTIONS_SHEET_ID,
  PROMOTIONS_SHEET_NAME,
};